name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 1.11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11.0.22+7
      
    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.2-test
      with:
        gradlePath: app/build.gradle
        versionCode: ${{github.run_number}}
        versionName: tests
    - name: Build debug APK
      run: ./gradlew assembleDemoDebug --stacktrace
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: debug-${{github.run_number}}.apk # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: app/build/outputs/apk/demo/debug/*.apk
#     - name: env
#       run: echo "::set-env name=gg::goodgame"
#     - name: envTest
# #       run: echo ${{env.gg}}      
#     - name: copy debug apk path
#       run: |-
#         files=(app/build/outputs/apk/debug/*.apk)
#         STAGING_APK_DIR=${files[0]}
#         echo '::set-env name=STAGING_APK_DIR::'$STAGING_APK_DIR
#     - name: Bump version
#       uses: chkfung/android-version-actions@v1.01
#       with:
#         gradlePath: app/build.gradle
#         versionCode: ${{env.gg}} ${env.gg}  $gg 
      
        
        
        
        
        
        
        
        
        
        
